GRANT ALTER ON SCHEMA:: [dbo] TO [AppUser_PolicyEX]
GO
GRANT CONTROL ON SCHEMA:: [dbo] TO [AppUser_PolicyEX]
GO
GRANT TAKE OWNERSHIP ON SCHEMA:: [dbo] TO [AppUser_PolicyEX]
GO
GRANT VIEW DEFINITION ON SCHEMA:: [dbo] TO [AppUser_PolicyEX]
GO
GRANT REFERENCES ON SCHEMA:: [dbo] TO [AppUser_PolicyEX]
GO
GRANT SELECT ON SCHEMA:: [dbo] TO [AppUser_PolicyEX]
GO
GRANT INSERT ON SCHEMA:: [dbo] TO [AppUser_PolicyEX]
GO
GRANT DELETE ON SCHEMA:: [dbo] TO [AppUser_PolicyEX]
GO
GRANT UPDATE ON SCHEMA:: [dbo] TO [AppUser_PolicyEX]
GO
GRANT EXECUTE ON SCHEMA:: [dbo] TO [AppUser_PolicyEX]
GO
GRANT VIEW CHANGE TRACKING ON SCHEMA:: [dbo] TO [AppUser_PolicyEX]
GO
